### PR TITLE
Filter prs below threshold

### PR DESCRIPTION
**Pull request by athuljayaraj**

### CODE REVIEW

**Comment by rushabh-v** [comment]
Going forward, the idea is to create an HTML doc of the thresholded version and convert that to an image + commit that image. 

And then if the same person wants to add that to readme he/she will need to add a line to his/her readme profile that adds a clickable image that links to the original (without threshold) HTML doc. (we can't put it directly into readmes as CSS isn't allowed to be used there). You can propose a better plan if you have anything!

**Comment by rushabh-v** [comment]
The thresholded version should not have the image and username of the person as it isn't required in the profile readmes.

**Comment by rushabh-v** [comment]
We will use `imgkit` for HTML to JPG conversion. for that, we will need to add `imgkit` in pip install and `wkhtmltopdf` in sudo apt install in the workflow. And use `imgkit.from_file('input.html', 'out.jpg')` for conversion.
`

**Comment by athuljayaraj** [comment]
Let's take this piece by piece. Let's move the hardcoded html from py file to template? And then let's add the image in README feature. Sound fine?

**Comment by rushabh-v** [comment]
Yes, sounds good.

So, for that, we will need to create separate files for each template. Also, we should rename `head.html` to `head`. And create all other templates as normal text files only. Also for the profile readme, we will need separate templates (without a profile picture, etc.)

Please feel free to reach out if you are stuck anywhere! Or you can also ask me to share the work.

**Comment by rushabh-v** [comment]
any updates on this?

**Comment by athuljayaraj** [comment]
I was a little tied up and will be so for two more days. We'll work on this the coming weekend?

**Comment by rushabh-v** [comment]
Sure, Thanks!

**Comment by rushabh-v** [comment]
Any updates? If you are short on time, I can merge this and complete the rest myself, no problem with that!

**Comment by rushabh-v** [comment]
Merged as I wanted to complete this earlier. Thanks for your contribution :)

**Pull request merged**
